### ISSUE TITLE
Update awscrt dependency for Python 3.9

### ISSUE THREAD

**Issue by Downchuck** [awslabs/amazon-transcribe-streaming-sdk#22]
awscrt has been updated a few times since the latest release - the update fixes compatibility with Python 3.9 and changes the aws body value from an enum to a string in signer.py.

@zdutta Who should I ping? The change in setup.py is simple, 0.10.2 is the latest:
https://pypi.org/project/awscrt/

The change in signer.py is pretty simple too, from ValueType and value_type to just Value and value, and the constructor is accessed instead of using a method (that method is now a string).

-Charles

**Comment by Downchuck** [comment]
@nateprewitt ping! looking to get issue #20 solved through updating awscrt to the latest release.

**Comment by Downchuck** [comment]
This issue does lead to #21

**Comment by nateprewitt** [comment]
We've just released v0.3.0 which bumps the version of CRT and should resolve this issue. I'm going to close this ticket out but please let us know if you're still seeing issues after upgrading. Thanks!
