### ISSUE TITLE
Can't figure out how to use it with AWS Lambda since awscrt is causing issue.

### ISSUE THREAD

**Issue by ReyanshKharga** [awslabs/amazon-transcribe-streaming-sdk#32]
I used the following command:

pip3 install amazon-transcribe aiofile -t .
But I get the following error when I use the layer in my lambda function:

Unable to import module 'lambda_function': No module named '_awscrt'
The same works fine with virtual environment locally. I'm not sure what's the exact issue.

I even tried adding the .whl file for awscrt seperately and package with lambda, but it didn't work.

Any kind of help will be greatly appreciated. Thanks!

**Comment by joguSD** [comment]
Hmmm, packaging the appropriate `manylinux1` wheel for your Python runtime should be the correct approach.

Are you still having issues with this?

**Comment by nateprewitt** [comment]
I'm going to resolve this since AWSCRT is being regularly used on Lambda now. Please let us know if you are still having issues.

**Comment by fhuthmacher** [comment]
mmh I am running into the same issue. Did anyone get this resolved? It's strange
