### ISSUE TITLE
Some language codes throw Exception

### ISSUE THREAD

**Issue by Marware** [awslabs/amazon-transcribe-streaming-sdk#40]
Hi,

While trying to use simple_file.py, changed the language code to ar-SA, threw this exception

`amazon_transcribe.exceptions.BadRequestException: 1 validation error detected: Value 'ar-SA' at 'languageCode' failed to satisfy constraint: Member must satisfy enum value set: [en-US, zh-CN, de-DE, it-IT, fr-FR, ko-KR, en-AU, pt-BR, ja-JP, es-US, fr-CA, en-GB]`

Works with other with solution but not with this code

Thanks

**Comment by nateprewitt** [comment]
Hi @Marware, this exception is being returned directly from the Amazon Transcribe service and not specific to this SDK. You can find the full list of supported LanguageCode values in the [AmazonTranscribe docs](https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartStreamTranscription.html#API_streaming_StartStreamTranscription_RequestParameters).

Could you provide some more info on where you're able to use `ar-SA` as a LanguageCode?

**Comment by nateprewitt** [comment]
Since we haven't had any follow up here, I'm going to resolve this for now. Please feel free to reopen if you have more info later. Thanks!
