### ISSUE TITLE
aws transcribe output 

### ISSUE THREAD

**Issue by haldernayan** [awslabs/amazon-transcribe-streaming-sdk#41]
aws transcribe is working fine, however the output is like this
This.
This is
This is a
This is a te
This is a test.
This is a test.

I only want the output as 
This is a test.

I understand the repeatation line comes as streaming is very fast. how to do streaming so that one word go only once. 

What changes need to be done in program simple_file.py orsimple_mic.py.

**Comment by nateprewitt** [comment]
Hi @haldernayan, the example provided in the Amazon Transcribe Streaming SDK documentation is intended to mirror the official [Transcribe documentation](https://docs.aws.amazon.com/transcribe/latest/dg/streaming.html). You'll find that each `Result` object we return [here](https://github.com/awslabs/amazon-transcribe-streaming-sdk/blob/develop/examples/simple_file.py#L21) has an `is_partial` flag on it. This denotes whether the translation results are complete. If you only output results with `result.is_partial is False`, it should be the complete lines you're referencing.

**Comment by Manjunath-PM** [comment]
> Hi @haldernayan, the example provided in the Amazon Transcribe Streaming SDK documentation is intended to mirror the official [Transcribe documentation](https://docs.aws.amazon.com/transcribe/latest/dg/streaming.html). You'll find that each `Result` object we return [here](https://github.com/awslabs/amazon-transcribe-streaming-sdk/blob/develop/examples/simple_file.py#L21) has an `is_partial` flag on it. This denotes whether the translation results are complete. If you only output results with `result.is_partial is False`, it should be the complete lines you're referencing.

hello nateprewitt can u explain neatly, how it can be done, even i need only the last output not all the text

**Comment by nateprewitt** [comment]
@Manjunath-PM, you would use the handler from the [example](https://github.com/awslabs/amazon-transcribe-streaming-sdk/blob/develop/examples/simple_file.py#L16-L23) linked above with the suggested conditional.

e.g.

```python
class MyEventHandler(TranscriptResultStreamHandler):
    async def handle_transcript_event(self, transcript_event: TranscriptEvent):
        results = transcript_event.transcript.results
        for result in results:
            if result.is_partial is False:
                for alt in result.alternatives:
                    print(alt.transcript)
```
