### ISSUE TITLE
AWS Transcribe Language model 

### ISSUE THREAD

**Issue by haldernayan** [awslabs/amazon-transcribe-streaming-sdk#43]
I Have build a custom language model.

How to pass that custom language model in simple_file.py  or   simple_mic.py.

**Comment by nateprewitt** [comment]
Hi @haldernayan, this should be resolved in the next release now that https://github.com/awslabs/amazon-transcribe-streaming-sdk/pull/70 is merged. You can accomplish this by uploading your model and passing the name as `language_model_name`.
