### ISSUE TITLE
Credentials issue

### ISSUE THREAD

**Issue by marinos123** [awslabs/amazon-transcribe-streaming-sdk#49]
is it possible to authenticate to aws using the awskey and secret key through the TranscribeStreamingClient instead of using the aws cli?

**Comment by nateprewitt** [comment]
Hi @marinos123, we provide a few ways to use credentials in the README. You should be able to use the CLI, Credentials specified in environment variables, or with a profile in ~/.aws/credentials.

If you're looking to specify credentials manually for your client, you may be interested in our [`StaticCredentialResolver`](https://github.com/awslabs/amazon-transcribe-streaming-sdk/blob/bed32f8a70c62ac22ed478f4ceaf048174fa6801/amazon_transcribe/auth.py#L49). You can instantiate it as shown below and pass it to your [`TranscribeStreamingClient`](https://github.com/awslabs/amazon-transcribe-streaming-sdk/blob/bed32f8a70c62ac22ed478f4ceaf048174fa6801/amazon_transcribe/client.py#L41) as the `credential_resolver`.

e.g.

```
cred_resolver = StaticCredentialResolver(
    access_key_id="AKIDEXAMPLE",
    secret_access_key="Secret12345",
    session_token="session_1"
)

client = TranscribeStreamingClient(region="us-west-2", credential_resolver=cred_resolver)
```

**Comment by marinos123** [comment]
Thanks a lot for the help!
