### ISSUE TITLE
No support for custom language model in this SDK For StartStreamTranscription

### ISSUE THREAD

**Issue by abhinav23dixit** [awslabs/amazon-transcribe-streaming-sdk#64]
Hi, I couldn't find support for custom language model in this python SDK, is that something I can add by any manner?

**Comment by abhinav23dixit** [comment]
it would be good if there is any reply from AWS people, been waiting for this feature for a while... no point of using websockets if you can include it in your python sdk itself

**Comment by nateprewitt** [comment]
Hi @abhinav23dixit, there's currently a PR (https://github.com/awslabs/amazon-transcribe-streaming-sdk/pull/70) in progress to add this.

**Comment by abhinav23dixit** [comment]
Hi @nateprewitt, looking forward to use this change ASAP. Thanks.

**Comment by nateprewitt** [comment]
We've merged #70 and it should be available in the next release. I'll resolve this as complete now. Thanks @abhinav23dixit.

**Comment by abhinav23dixit** [comment]
Thanks @nateprewitt , when is the next release?

**Comment by nateprewitt** [comment]
We currently have the PR staged in #71. You can track that for release progress.
