### ISSUE TITLE
failed to satisfy constraint

### ISSUE THREAD

**Issue by subramanichetan** [awslabs/amazon-transcribe-streaming-sdk#74]
BadRequestException: An error occurred (BadRequestException) when calling the CreateLanguageModel operation: 1 validation error detected: Value 'arn:aws:iam::886543613495:user/Administrator' at 'inputDataConfig.dataAccessRoleArn' failed to satisfy constraint: Member must satisfy regular expression pattern: ^arn:(aws|aws-cn|aws-us-gov|aws-iso-{0,1}[a-z]{0,1}):iam::[0-9]{0,63}:role/[A-Za-z0-9:_/+=,@.-]{0,1024}$

**Comment by nateprewitt** [comment]
Hi @subramanichetan, this needs to be a Role ARN but you're providing a User ARN which is incompatible. You'll need to create or provide an appropriate role as specified in the [Transcribe Streaming documentation](https://docs.aws.amazon.com/transcribe/latest/APIReference/API_InputDataConfig.html#transcribe-Type-InputDataConfig-DataAccessRoleArn). You can find resources to help with that process in the [Creating IAM roles ](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create.html)docs.
