### ISSUE TITLE
Missing "vocab_filter_name" in request

### ISSUE THREAD

**Issue by n1cefeatures** [awslabs/amazon-transcribe-streaming-sdk#8]
Hi Team,

`vocab_filter_name` parameter is missing in [client.py](https://github.com/awslabs/amazon-transcribe-streaming-sdk/blob/c51c3d28db993ce5011fd574c37dbb61e8711f64/amazon_transcribe/client.py#L70)

The missing parameter exists in [the official API](https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartStreamTranscription.html#API_streaming_StartStreamTranscription_RequestSyntax).

Currently it is not possible to stream audio with a created vocabulary filter.

With best regards,
n1cefeatures

**Comment by joguSD** [comment]
Thanks for reporting this. Looks like the API had a few updates since the original implementation. We'll take a look at implementing these updates.
